example/config/routes.rb
Rails.application.routes.draw do
  root 'invoices#index'
  resources :invoices

end

example/app/models/invoice.rb
class Invoice < ActiveRecord::Base
  include SerializeHasMany::Concern
  serialize_has_many :line_items, LineItem, using: JSON, validate: true,
    reject_if: Proc.new{ |item| !item[:name].present? }
end

example/app/models/line_item.rb
class LineItem
  include ActiveModel::Model

  attr_accessor :name
  attr_accessor :price
  attr_accessor :quantity

  validates :name, presence: true
  validates :price, numericality: { greater_than: 0 }, presence: true
  validates :quantity, numericality: { greater_than: 0 }, presence: true

  def attributes
    { name: name, price: price, quantity: quantity }
  end
end

example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

example/app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    if @invoice.save
      redirect_to @invoice, notice: 'Invoice was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    if @invoice.update(invoice_params)
      redirect_to @invoice, notice: 'Invoice was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    redirect_to invoices_url, notice: 'Invoice was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:name, line_items_attributes: [ :name, :price, :quantity ])
    end
end

example/app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :line_items do |f_item| %>
    <fieldset>
      <legend>Line Item</legend>
      <div class="field">
        <%= f_item.label :name %><br>
        <%= f_item.text_field :name %>
      </div>
      <div class="field">
        <%= f_item.label :price %><br>
        <%= f_item.text_field :price %>
      </div>
      <div class="field">
        <%= f_item.label :quantity %><br>
        <%= f_item.text_field :quantity %>
      </div>
    </fieldset>
  <% end %>

  <%= f.fields_for :line_items, LineItem.new do |f_item| %>
    <fieldset>
      <legend>Line Item</legend>
      <div class="field">
        <%= f_item.label :name %><br>
        <%= f_item.text_field :name %>
      </div>
      <div class="field">
        <%= f_item.label :price %><br>
        <%= f_item.text_field :price %>
      </div>
      <div class="field">
        <%= f_item.label :quantity %><br>
        <%= f_item.text_field :quantity %>
      </div>
    </fieldset>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

example/app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

example/app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Line items</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.name %></td>
        <td><%= invoice.line_items.count %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

example/app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

example/app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @invoice.name %>
</p>

<p>
  <strong>Line items:</strong>
  <%= @invoice.line_items %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>